### PR TITLE
raw: Use libc _SC_2_C_VERSION, not literal number

### PR DESCRIPTION
**Pull request by joshlf**

### CODE REVIEW

**Comment by gmjosack** [comment]
Hey @joshlf Looks like the `test_hugepage_supported` test is failing for this and another pull request today on nightly. Would you mind fixing that or disabling the test if it's not high signal before I merge these? Would like to make sure the build is healthy/reliable before merging new diffs.

**Comment by joshlf** [comment]
Hey, so I've narrowed it down to `lstat` spuriously failing. You can see in [this build](https://travis-ci.org/ZeroCostGoods/sysconf.rs/jobs/358619957) that running `ls -lR` indicates that the path `/sys/kernel/mm/hugepages/hugepages-2048kB/` exists, but `lstat` fails with `ENOENT` on that same path. After reading the `lstat` man page and trying a few things (e.g., with and without a trailing slash on the path), I'm at a loss for what's going on. Do you have any insight here?

**Comment by gmjosack** [comment]
Sorry for the super long delay here. I looked a bit but didn't have any thing stand out. I've set the test to ignore by default for now so that it doesn't block other changes from going in.

I manually merged your original commit without all the temp commits and it's been published in https://crates.io/crates/sysconf/0.3.2

**Comment by joshlf** [comment]
Looks like you might want to revert this. It's failing on my local machine because the constant was removed from libc here: https://github.com/rust-lang/libc/commit/773aab8293f972956617751af48a2be2a7187696.

**Comment by gmjosack** [comment]
Thanks for the heads up. I've reverted on master and published https://crates.io/crates/sysconf/0.3.3

**Pull request closed without merging**
