### PR TITLE
AppVeyor: Initial commit

### PR DESCRIPTION
**Pull request by joshlf**
Also bumps version to 0.3.1.

### CODE REVIEW

**Comment by gmjosack** [comment]
I believe you need to rebase your changes off of master. This PR doesn't have your latest changes and is failing to find kernel32.

**Comment by gmjosack** [comment]
So far the appveyor builds have been kind of flaky.

1 job out of each 3 different builds has failed with

```
Build started
git clone -q https://github.com/ZeroCostGoods/sysconf.rs.git C:\projects\sysconf-rs
git fetch -q origin +refs/pull/10/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
Error downloading remote file: One or more errors occurred.
Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.
Command exited with code 2
```

This is exacerbated by taking an hour to run through each of the 2 builds that get triggered.

A couple thoughts:

* Maybe we skip running beta to save on 8 builds
* Is there a way to make the appveyor download retry? I noticed deisel switched to curl in order to get retries because of the same issue. https://github.com/diesel-rs/diesel/pull/883/files

Thoughts?

**Comment by joshlf** [comment]
Ah good catch! I'll do both since I think supporting nightly should get us most of the benefits of supporting beta.

**Comment by joshlf** [comment]
Should be ready to publish 0.3.1 when you're ready, @gmjosack . Merging now.

**Comment by gmjosack** [comment]
Published: https://crates.io/crates/sysconf/0.3.1

**Pull request merged**
